import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useCardStore } from "../../store/useCardStore";
import styles from "./AddCardModal.module.css";

const AddCardModal: React.FC = () => {
  const { isModalOpen, isLoading, closeModal, addCard } = useCardStore();

  const [name, setName]       = useState('');
  const [error, setError]     = useState('');
  const [touched, setTouched] = useState(false);

  const inputRef    = useRef<HTMLInputElement>(null);
  const overlayRef  = useRef<HTMLDivElement>(null);

  // Focus input when modal opens; reset state when it closes
  useEffect(() => {
    if (isModalOpen) {
      setTimeout(() => inputRef.current?.focus(), 60);
    } else {
      setName('');
      setError('');
      setTouched(false);
    }
  }, [isModalOpen]);

  // Close on Escape
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isModalOpen) closeModal();
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [isModalOpen, closeModal]);

  // ── Validation ────────────────────────────────────────────────────────────

  const validate = useCallback((value: string): string => {
    const trimmed = value.trim();
    if (trimmed.length === 0)  return 'Cardholder name is required.';
    if (trimmed.length < 2)    return 'Name must be at least 2 characters.';
    if (trimmed.length > 28)   return 'Name must be 28 characters or fewer.';
    if (!/^[a-zA-Z\s\-'.]+$/.test(trimmed))
      return 'Name may only contain letters, spaces, hyphens, and apostrophes.';
    return '';
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setName(val);
    if (touched) setError(validate(val));
  };

  const handleBlur = () => {
    setTouched(true);
    setError(validate(name));
  };

  // ── Submit ────────────────────────────────────────────────────────────────

  const handleSubmit = async () => {
    setTouched(true);
    const validationError = validate(name);
    if (validationError) {
      setError(validationError);
      inputRef.current?.focus();
      return;
    }
    await addCard(name);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') handleSubmit();
  };

  // ── Overlay click to close ────────────────────────────────────────────────

  const handleOverlayClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if (e.target === overlayRef.current) closeModal();
  };

  if (!isModalOpen) return null;

  return (
    <div
      className={styles.overlay}
      ref={overlayRef}
      onClick={handleOverlayClick}
      role="dialog"
      aria-modal="true"
      aria-labelledby="modal-title"
    >
      <div className={styles.modal}>
        <h2 className={styles.title} id="modal-title">Add New Card</h2>
        <p className={styles.subtitle}>
          Enter the cardholder name. The card number and expiry date will be
          randomly generated by the system.
        </p>

        {/* Form */}
        <div className={styles.formGroup}>
          <label htmlFor="card-name" className={styles.label}>
            Name on card
          </label>
          <input
            id="card-name"
            ref={inputRef}
            type="text"
            className={`${styles.input} ${error && touched ? styles.inputError : ''}`}
            placeholder="e.g. Jane Smith"
            value={name}
            onChange={handleChange}
            onBlur={handleBlur}
            onKeyDown={handleKeyDown}
            maxLength={28}
            autoComplete="off"
            disabled={isLoading}
            aria-describedby={error ? 'card-name-error' : undefined}
            aria-invalid={!!error && touched}
          />
          {error && touched && (
            <p id="card-name-error" className={styles.errorMsg} role="alert">
              {error}
            </p>
          )}
        </div>

        {/* Actions */}
        <div className={styles.actions}>
          <button
            className={styles.btnCancel}
            onClick={closeModal}
            disabled={isLoading}
          >
            Cancel
          </button>
          <button
            className={styles.btnSubmit}
            onClick={handleSubmit}
            disabled={isLoading}
          >
            {isLoading ? 'Adding…' : 'Add card'}
          </button>
        </div>
      </div>
    </div>
  );
};

export default AddCardModal;